name: flutter_icon_browser
description: The misssing icon browser for Flutter.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flex_color_scheme: ^7.1.2
  fluentui_system_icons: ^1.1.203
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  yaru_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
